#!/usr/bin/python
from supervisor.supervisord import main

# __doc__ required to make supervisord -h work
from supervisor.supervisord import __doc__

import os
import json

def save_ssr():
    ss = {}
    with open('/root/script/shadowsocks/shadowsocks.json', 'r') as f:
        config = json.load(f)
    config = ss
    config['ssr_password'] = os.environ["SSR_PASSWORD"]
    try:
        with open('/root/script/shadowsocks/shadowsocks.json', 'w') as f:
            json.dump(config, f, indent=4, sort_keys=True)
        return 200
    except:
        return 201

def save_env():
    dd = {
        "token": os.environ["TOKEN"],
        "secret": os.environ["SECRET"],
        "smtp_host" : os.environ["SMTP_HOST"],
        "ssl_port" : os.environ["SSL_PORT"],
        "mail_username" : os.environ["MAIL_USERNAME"],
        "mail_password" : os.environ["MAIL_PASSWORD"],
        "mail_to" : os.environ["MAIL_TO"],
        "ssr_password" : os.environ["SSR_PASSWORD"],
        "server_ip" : "127.0.0.1:14587"
    }
    with open('/root/script/config.json', 'r') as f:
        config = json.load(f)
    config = dd
    try:
        with open('/root/script/config.json', 'w') as f:
            json.dump(config, f, indent=4, sort_keys=True)
        os.system("echo \"root:%s\" | chpasswd" % os.environ["SSH_PASSWORD"])
        os.system("python /root/script/update.py >> /root/update.log 2>&1 &")
        return 200
    except:
        return 201

if __name__ == '__main__':
    save_ssr()
    save_env()
    main()