#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'supervisor==3.1.4','console_scripts','supervisord'
__requires__ = 'supervisor==3.1.4'
import sys
import json
import os
from pkg_resources import load_entry_point

def save(token, secret):
    dd = {
        "token" : token,
        "secret" : secret,
    }
    with open('/root/script/config.json', 'r') as f:
        config = json.load(f)
    config = dd
    try:
        with open('/root/script/config.json', 'w') as f:
            json.dump(config, f, indent=4, sort_keys=True)
        return 200
    except:
        return 201

if __name__ == '__main__':    
    save(os.environ["TOKEN"], os.environ["SECRET"])
    sys.exit(
        load_entry_point('supervisor==3.1.4', 'console_scripts', 'supervisord')()
    )
